/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilsRouteRouteImport } from './routes/utils/route'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilsIndexRouteImport } from './routes/utils/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs/new'
import { Route as AdminBlogsSlugRouteImport } from './routes/admin/blogs/$slug'

const UtilsRouteRoute = UtilsRouteRouteImport.update({
  id: '/utils',
  path: '/utils',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilsIndexRoute = UtilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UtilsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsSlugRoute = AdminBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/utils': typeof UtilsRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/utils/': typeof UtilsIndexRoute
  '/admin/blogs/$slug': typeof AdminBlogsSlugRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/utils': typeof UtilsIndexRoute
  '/admin/blogs/$slug': typeof AdminBlogsSlugRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/utils': typeof UtilsRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/utils/': typeof UtilsIndexRoute
  '/admin/blogs/$slug': typeof AdminBlogsSlugRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/utils'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/utils/'
    | '/admin/blogs/$slug'
    | '/admin/blogs/new'
    | '/admin/blogs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/utils'
    | '/admin/blogs/$slug'
    | '/admin/blogs/new'
    | '/admin/blogs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/utils'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/utils/'
    | '/admin/blogs/$slug'
    | '/admin/blogs/new'
    | '/admin/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  UtilsRouteRoute: typeof UtilsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utils': {
      id: '/utils'
      path: '/utils'
      fullPath: '/utils'
      preLoaderRoute: typeof UtilsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utils/': {
      id: '/utils/'
      path: '/'
      fullPath: '/utils/'
      preLoaderRoute: typeof UtilsIndexRouteImport
      parentRoute: typeof UtilsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs/$slug': {
      id: '/admin/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/admin/blogs/$slug'
      preLoaderRoute: typeof AdminBlogsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsSlugRoute: typeof AdminBlogsSlugRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsSlugRoute: AdminBlogsSlugRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface UtilsRouteRouteChildren {
  UtilsIndexRoute: typeof UtilsIndexRoute
}

const UtilsRouteRouteChildren: UtilsRouteRouteChildren = {
  UtilsIndexRoute: UtilsIndexRoute,
}

const UtilsRouteRouteWithChildren = UtilsRouteRoute._addFileChildren(
  UtilsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  UtilsRouteRoute: UtilsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
