/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilsRouteRouteImport } from './routes/utils/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilsIndexRouteImport } from './routes/utils/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'

const UtilsRouteRoute = UtilsRouteRouteImport.update({
  id: '/utils',
  path: '/utils',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilsIndexRoute = UtilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UtilsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/utils': typeof UtilsRouteRouteWithChildren
  '/blog': typeof BlogIndexRoute
  '/utils/': typeof UtilsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogIndexRoute
  '/utils': typeof UtilsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/utils': typeof UtilsRouteRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/utils/': typeof UtilsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/utils' | '/blog' | '/utils/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/utils'
  id: '__root__' | '/' | '/utils' | '/blog/' | '/utils/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UtilsRouteRoute: typeof UtilsRouteRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utils': {
      id: '/utils'
      path: '/utils'
      fullPath: '/utils'
      preLoaderRoute: typeof UtilsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utils/': {
      id: '/utils/'
      path: '/'
      fullPath: '/utils/'
      preLoaderRoute: typeof UtilsIndexRouteImport
      parentRoute: typeof UtilsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UtilsRouteRouteChildren {
  UtilsIndexRoute: typeof UtilsIndexRoute
}

const UtilsRouteRouteChildren: UtilsRouteRouteChildren = {
  UtilsIndexRoute: UtilsIndexRoute,
}

const UtilsRouteRouteWithChildren = UtilsRouteRoute._addFileChildren(
  UtilsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UtilsRouteRoute: UtilsRouteRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
